#!/usr/bin/env python3
"""
sync_skill_pointers.py -- keep per-tool skill pointers in sync.

The skills in `.agents/skills/` are canonical. Some agents look for
skills in their own directory instead, so this writes a thin pointer per
tool that carries the same `name`/`description` frontmatter (which is
what an agent matches against when deciding to use a skill) and a body
that says to read the canonical file.

One source of truth: the pointer never contains workflow instructions,
so the two cannot drift. Run this after editing a canonical skill's
frontmatter, or after adding a skill.

  python3 scripts/sync_skill_pointers.py
  python3 scripts/sync_skill_pointers.py --check   # verify, change nothing

`--check` exits 1 if anything is stale, which makes it usable in CI or a
pre-commit hook.

Stdlib only. No pip install required.
"""

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from wiki_config import VAULT_ROOT  # noqa: E402

CANONICAL = VAULT_ROOT / ".agents" / "skills"

# Add a directory here to support another agent that wants its own
# skills folder. Pointers are generated, so adding one costs nothing.
POINTER_DIRS = [VAULT_ROOT / ".claude" / "skills"]


def read_frontmatter(path):
    text = path.read_text(encoding="utf-8")
    m = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    if not m:
        raise SystemExit(f"{path} has no YAML frontmatter block")
    block = m.group(1)

    def field(key):
        f = re.search(rf"^{key}:\s*(.+)$", block, re.M)
        if not f:
            raise SystemExit(f"{path} frontmatter is missing `{key}:`")
        return f.group(1).strip()

    return field("name"), field("description")


def pointer_text(slug, name, description):
    rel = f".agents/skills/{slug}/SKILL.md"
    return (
        f"---\nname: {name}\ndescription: {description}\n---\n\n"
        f"# {name}\n\n"
        f"This is a pointer. The skill itself lives at\n"
        f"`{rel}`, which is the single source of\n"
        f"truth shared by every agent that works in this vault.\n\n"
        f"**Read `{rel}` in full, then follow it.**\n"
        f"Read `AGENTS.md` first if you have not already.\n\n"
        f"Do not edit this file to change the workflow — edit the canonical\n"
        f"one, or the agents reading it will drift apart.\n"
    )


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--check", action="store_true",
                    help="report staleness without writing; exit 1 if stale")
    args = ap.parse_args()

    if not CANONICAL.is_dir():
        raise SystemExit(f"No canonical skills directory: {CANONICAL}")

    skills = sorted(d for d in CANONICAL.iterdir() if (d / "SKILL.md").is_file())
    if not skills:
        raise SystemExit(f"No skills found under {CANONICAL}")

    stale, written, expected = [], [], set()
    for d in skills:
        name, desc = read_frontmatter(d / "SKILL.md")
        want = pointer_text(d.name, name, desc)
        for pdir in POINTER_DIRS:
            out = pdir / d.name / "SKILL.md"
            expected.add(out)
            if out.exists() and out.read_text(encoding="utf-8") == want:
                continue
            rel = out.relative_to(VAULT_ROOT)
            if args.check:
                stale.append(f"stale or missing: {rel}")
            else:
                out.parent.mkdir(parents=True, exist_ok=True)
                out.write_text(want, encoding="utf-8")
                written.append(str(rel))

    # A pointer whose canonical skill was deleted or renamed would keep
    # advertising a workflow that no longer exists.
    for pdir in POINTER_DIRS:
        if not pdir.is_dir():
            continue
        for out in sorted(pdir.rglob("SKILL.md")):
            if out not in expected:
                rel = out.relative_to(VAULT_ROOT)
                msg = f"orphaned pointer (no canonical skill): {rel}"
                stale.append(msg) if args.check else print(f"  ! {msg} -- delete it")

    if args.check:
        if stale:
            print(f"{len(stale)} issue(s):")
            for s in stale:
                print(f"  - {s}")
            print("\nRun: python3 scripts/sync_skill_pointers.py")
            return 1
        print(f"All pointers up to date ({len(skills)} skill(s)).")
        return 0

    for w in written:
        print(f"wrote {w}")
    print(f"{len(skills)} skill(s); {len(written)} pointer(s) updated.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
